app_code: bk_gsekit
app_name: GSEKIT
app_name_en: GSEKIT
is_use_celery: true
author: 蓝鲸智云
introduction: 进程配置管理
introduction_en: process&config manager
version: 1.0.18
category: 运维工具
language_support: 英语,中文
desktop:
  width: 1300
  height: 720
  is_max: true
container:
  memory: 4096
