# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸 (Blueking) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at https://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.6 on 2020-12-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gsekit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GsekitProcessToCCProcessTemplateMap",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务ID")),
                ("gsekit_process_id", models.IntegerField(verbose_name="金枪鱼进程ID")),
                ("cc_process_template_id", models.IntegerField(verbose_name="CC3.0进程模板ID")),
            ],
            options={"verbose_name": "金枪鱼进程映射表", "verbose_name_plural": "金枪鱼进程映射表"},
        ),
        migrations.CreateModel(
            name="MigrationStatus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务ID")),
                (
                    "migrate_obj",
                    models.CharField(
                        choices=[("process", "进程"), ("config", "配置文件"), ("relation", "绑定关系")],
                        max_length=16,
                        verbose_name="迁移对象",
                    ),
                ),
                ("is_migrated", models.BooleanField(default=False, verbose_name="是否已迁移")),
            ],
            options={"verbose_name": "迁移状态", "verbose_name_plural": "迁移状态"},
        ),
        migrations.AddField(
            model_name="job", name="expression_scope", field=models.JSONField(default=dict, verbose_name="表达式范围"),
        ),
    ]
