# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸 (Blueking) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at https://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.6 on 2020-12-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gsekit", "0002_auto_20201221_1055"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processinst", options={"verbose_name": "进程实例", "verbose_name_plural": "进程实例"},
        ),
        migrations.RemoveField(model_name="process", name="id",),
        migrations.AlterField(
            model_name="migrationstatus",
            name="migrate_obj",
            field=models.CharField(
                choices=[("process", "进程"), ("config", "配置文件"), ("relation", "绑定关系"), ("process_inst", "进程实例")],
                max_length=16,
                verbose_name="迁移对象",
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="bk_process_id",
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name="进程ID"),
        ),
    ]
