# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸 (Blueking) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at https://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.6 on 2021-01-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gsekit", "0003_auto_20201222_2142"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="expression",
            field=models.TextField(max_length=256, null=True, verbose_name="实例表达式"),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待中"),
                    ("running", "执行中"),
                    ("succeeded", "执行成功"),
                    ("failed", "执行失败"),
                    ("ignored", "已忽略"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
                verbose_name="任务状态",
            ),
        ),
        migrations.AlterField(
            model_name="jobtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待中"),
                    ("running", "执行中"),
                    ("succeeded", "执行成功"),
                    ("failed", "执行失败"),
                    ("ignored", "已忽略"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
                verbose_name="任务状态",
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="process_status",
            field=models.IntegerField(db_index=True, default=2, verbose_name="进程状态"),
        ),
        migrations.AlterField(
            model_name="processinst",
            name="process_status",
            field=models.IntegerField(db_index=True, default=2, verbose_name="进程状态"),
        ),
    ]
