# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸 (Blueking) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at https://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.6 on 2021-04-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gsekit", "0006_auto_20210226_1622"),
    ]

    operations = [
        migrations.AddField(
            model_name="bscpconfig",
            name="file_name",
            field=models.CharField(default="", max_length=64, verbose_name="文件名"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bscpconfig",
            name="path",
            field=models.CharField(default="", max_length=256, verbose_name="文件路径"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="configinstance",
            name="name",
            field=models.CharField(default="", max_length=64, verbose_name="文件名"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待执行"),
                    ("running", "正在执行"),
                    ("succeeded", "执行成功"),
                    ("failed", "执行失败"),
                    ("ignored", "已忽略"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
                verbose_name="任务状态",
            ),
        ),
        migrations.AlterField(
            model_name="jobtask",
            name="err_code",
            field=models.IntegerField(db_index=True, default=1, verbose_name="错误码"),
        ),
        migrations.AlterField(
            model_name="jobtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待执行"),
                    ("running", "正在执行"),
                    ("succeeded", "执行成功"),
                    ("failed", "执行失败"),
                    ("ignored", "已忽略"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
                verbose_name="任务状态",
            ),
        ),
        migrations.AlterField(
            model_name="migrationstatus",
            name="migrate_obj",
            field=models.CharField(
                choices=[
                    ("process", "进程"),
                    ("config", "配置文件"),
                    ("relation", "绑定关系"),
                    ("process_inst", "进程实例"),
                    ("iam", "权限"),
                ],
                max_length=16,
                verbose_name="迁移对象",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bscpconfig", unique_together={("app_id", "config_template_id", "file_name", "path")},
        ),
    ]
