# Generated by Django 3.2.4 on 2022-09-25 13:58

import apps.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gsekit", "0011_auto_20220509_2115"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("config_instance_id", models.BigIntegerField(db_index=True, verbose_name="配置实例 ID")),
                ("job_instance_id", models.BigIntegerField(db_index=True, verbose_name="作业实例ID")),
                ("content", apps.utils.models.CompressedTextField(verbose_name="快照内容")),
                ("sha256", models.CharField(max_length=64, verbose_name="SHA256")),
            ],
            options={
                "verbose_name": "现网配置快照（ConfigSnapshot）",
                "verbose_name_plural": "现网配置快照（ConfigSnapshot）",
            },
        ),
        migrations.AlterField(
            model_name="job",
            name="job_action",
            field=models.CharField(
                choices=[
                    ("generate", "生成"),
                    ("release", "下发"),
                    ("diff", "对比"),
                    ("start", "启动"),
                    ("stop", "停止"),
                    ("restart", "重启"),
                    ("reload", "重载"),
                    ("force_stop", "强制停止"),
                    ("set_auto", "托管"),
                    ("unset_auto", "取消托管"),
                ],
                db_index=True,
                max_length=16,
                verbose_name="动作",
            ),
        ),
    ]
