# Generated by Django 3.2.4 on 2022-09-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gsekit", "0012_auto_20220925_2158"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_action",
            field=models.CharField(
                choices=[
                    ("generate", "生成"),
                    ("release", "下发"),
                    ("diff", "检查"),
                    ("start", "启动"),
                    ("stop", "停止"),
                    ("restart", "重启"),
                    ("reload", "重载"),
                    ("force_stop", "强制停止"),
                    ("set_auto", "托管"),
                    ("unset_auto", "取消托管"),
                ],
                db_index=True,
                max_length=16,
                verbose_name="动作",
            ),
        ),
    ]
