# Generated by Django 3.2.15 on 2025-04-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gsekit", "0015_auto_20230714_1639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="bk_app_code",
            field=models.CharField(default="gsekit2", max_length=32, verbose_name="蓝鲸应用ID"),
        ),
    ]
