# Generated by Django 3.2.15 on 2025-04-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gsekit", "0016_alter_job_bk_app_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务 ID")),
                ("bk_biz_name", models.CharField(max_length=255, verbose_name="业务名称")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "业务信息",
                "verbose_name_plural": "业务信息",
            },
        ),
    ]
