name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-18.04
    env:
      OS: ubuntu-18.04
      PYTHON: "3.6"
      DJANGO_SETTINGS_MODULE: "settings"
      DEBUG: true
      BKPAAS_ENGINE_REGION: "open"
      RUN_ENV: "open"
      APP_CODE: "bk_gsekit"
      APP_ID: "bk_gsekit"
      SECRET_KEY: "12345678-1234-5678-1234-123456789012"
      APP_TOKEN: "12345678-1234-5678-1234-123456789012"
      BK_PAAS_HOST: "http://127.0.0.1"
      BK_IAM_V3_INNER_HOST: "127.0.0.1"
      BROKER_URL: "redis://localhost:6379/0"
      BK_MYSQL_NAME: "bk_gsekit"
      BK_MYSQL_USER: "root"
      BK_MYSQL_PASSWORD: "root"
      BK_MYSQL_HOST: "localhost"
      BK_MYSQL_PORT: 3306
      BK_MYSQL_TEST_NAME: "bk_gsekit_test"
      WORKFLOW_DIR: "scripts/workflows"
      CODECOV_TOKEN: "f36b5663-d697-4020-9e8e-47523082e8ef"
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.6
    - name: Setup Mysql
      run: |
        sudo systemctl start mysql.service
    - name: Generate Report
      run: |
        ./scripts/workflows/bk_ci.sh
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1